### ISSUE TITLE
Бойлер для пет-проектов (вставка фото фоном)

### ISSUE THREAD

**Issue by SVP-IRISKA** [shut56/mern-boilerplate#9]
Есть фото. Хочу поставить как   
background: url('/assets/images/orange.jpg') center center/cover no-repeat;
или   background: url('../images/orange.jpg') center center/cover no-repeat;

Выдает ошибку в терминале:
ERROR in ./client/styles/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Консоль:
Uncaught Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.62.1 compiled with 2 errors in 4810 ms

В таком виде все нормально если путь в style.css из инета:   background: url('https://i.pinimg.com/736x/c4/7d/40/c47d403a93346f3f164571130b2c97d7.jpg') center center/cover no-repeat;

Просто вставить фото в jsx компонента, тоже все нормально: 
<div><img src="/assets/images/orange.jpg" alt="fff" /></div>

так не работает:
      <div><img src="../images/orange.jpg" alt="fff" /></div>

**Comment by shut56** [comment]
Добавил опцию `url: false` для css-loader. Должно работать.
